export interface BaseService {
  id: string;
  name: string;
  description: string;
  category: string;
}

export interface ProblemArea {
  id: string;
  name: string;
  description: string;
}

export interface BodyRegion {
  id: string;
  name: string;
  description: string;
  icon: string;
}

export interface TreatmentArea {
  id: string;
  name: string;
  regionId: string;
  description?: string;
}

export interface TreatmentZone {
  id: string;
  name: string;
  areaId: string;
  description?: string;
  isPopular?: boolean;
}

export interface CompositeService {
  id?: string;
  baseServiceId: string;
  selectedEquipment: string[];
  selectedProblems: string[];
  selectedAreas: string[];
  selectedZones?: string[]; // Add zones to composite services
  customName: string;
  description: string;
  autoGeneratedKeywords: string[];
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export const BASE_SERVICES: BaseService[] = [
  {
    id: 'microneedling',
    name: 'Microneedling',
    description: 'Kollagenstimulering och hudförnyelse',
    category: 'aesthetic'
  },
  {
    id: 'ansiktsbehandling',
    name: 'Ansiktsbehandling',
    description: 'Grundläggande hudvård och rengöring',
    category: 'skincare'
  },
  {
    id: 'laserbehandling',
    name: 'Laserbehandling',
    description: 'Laserbaserade behandlingar',
    category: 'laser'
  },
  {
    id: 'kemisk-peeling',
    name: 'Kemisk Peeling',
    description: 'Syrabehandlingar för hudförnyelse',
    category: 'chemical'
  },
  {
    id: 'konsultation',
    name: 'Konsultation',
    description: 'Analys och rådgivning',
    category: 'consultation'
  }
];

export const PROBLEM_AREAS: ProblemArea[] = [
  {
    id: 'acne',
    name: 'Akne',
    description: 'Inflammerad och icke-inflammerad akne'
  },
  {
    id: 'scars',
    name: 'Ärr',
    description: 'Akneärr och andra hudärr'
  },
  {
    id: 'wrinkles',
    name: 'Rynkor',
    description: 'Fina linjer och djupare rynkor'
  },
  {
    id: 'pigmentation',
    name: 'Pigmentering',
    description: 'Ojämn pigmentering och fläckar'
  },
  {
    id: 'dry-skin',
    name: 'Torr hud',
    description: 'Uttorkad och irriterad hud'
  },
  {
    id: 'large-pores',
    name: 'Stora porer',
    description: 'Förstorade och synliga porer'
  },
  {
    id: 'dullness',
    name: 'Matt hud',
    description: 'Livlös och glansös hud'
  },
  {
    id: 'rosacea',
    name: 'Rosacea',
    description: 'Rodnad och känslig hud'
  },
  {
    id: 'hair-removal',
    name: 'Hårborttagning',
    description: 'Oönskad hårväxt'
  },
  {
    id: 'vascular-lesions',
    name: 'Kärlförändringar',
    description: 'Synliga blodkärl och rosacearodnad'
  }
];

export const BODY_REGIONS: BodyRegion[] = [
  {
    id: 'head',
    name: 'Huvud',
    description: 'Ansikte och hals',
    icon: '👤'
  },
  {
    id: 'upper-body',
    name: 'Överkropp',
    description: 'Bröst, armar och axlar',
    icon: '🫸'
  },
  {
    id: 'lower-body',
    name: 'Underkropp',
    description: 'Ben, höfter och fötter',
    icon: '🦵'
  },
  {
    id: 'intim',
    name: 'Intim',
    description: 'Intimområden',
    icon: '🔒'
  }
];

export const TREATMENT_AREAS: TreatmentArea[] = [
  // Head region
  {
    id: 'face',
    name: 'Ansikte',
    regionId: 'head',
    description: 'Hela ansiktsområdet'
  },
  {
    id: 'neck',
    name: 'Hals',
    regionId: 'head',
    description: 'Halsområdet'
  },
  
  // Upper body region
  {
    id: 'chest',
    name: 'Bröst',
    regionId: 'upper-body',
    description: 'Bröstkorg och dekolletage'
  },
  {
    id: 'arms',
    name: 'Armar',
    regionId: 'upper-body',
    description: 'Över- och underarmar'
  },
  {
    id: 'shoulders',
    name: 'Axlar',
    regionId: 'upper-body',
    description: 'Axelområdet'
  },
  {
    id: 'hands',
    name: 'Händer',
    regionId: 'upper-body',
    description: 'Händer och fingrar'
  },
  
  // Lower body region
  {
    id: 'legs',
    name: 'Ben',
    regionId: 'lower-body',
    description: 'Lår och vader'
  },
  {
    id: 'feet',
    name: 'Fötter',
    regionId: 'lower-body',
    description: 'Fötter och tår'
  },
  
  // Intim region
  {
    id: 'bikini',
    name: 'Bikiniområde',
    regionId: 'intim',
    description: 'Intimområdet'
  },
  {
    id: 'brazilian',
    name: 'Brazilian',
    regionId: 'intim',
    description: 'Fullständig intimbehandling'
  }
];

export const TREATMENT_ZONES: TreatmentZone[] = [
  // Face zones
  {
    id: 'forehead',
    name: 'Panna',
    areaId: 'face'
  },
  {
    id: 'eyes',
    name: 'Ögonområde',
    areaId: 'face',
    description: 'Runt ögonen och ögonlock'
  },
  {
    id: 'cheeks',
    name: 'Kinder',
    areaId: 'face'
  },
  {
    id: 'nose',
    name: 'Näsa',
    areaId: 'face'
  },
  {
    id: 'mouth',
    name: 'Mun',
    areaId: 'face',
    description: 'Runt munnen och läppar'
  },
  {
    id: 'chin',
    name: 'Haka',
    areaId: 'face'
  },
  {
    id: 'jawline',
    name: 'Käklinje',
    areaId: 'face'
  },
  
  // Neck zones
  {
    id: 'front-neck',
    name: 'Främre hals',
    areaId: 'neck'
  },
  {
    id: 'back-neck',
    name: 'Nacke',
    areaId: 'neck'
  },
  
  // Chest zones
  {
    id: 'decolletage',
    name: 'Dekolletage',
    areaId: 'chest'
  },
  {
    id: 'chest-full',
    name: 'Hela bröstet',
    areaId: 'chest'
  },
  
  // Arms zones
  {
    id: 'upper-arms',
    name: 'Överarmar',
    areaId: 'arms'
  },
  {
    id: 'lower-arms',
    name: 'Underarmar',
    areaId: 'arms'
  },
  {
    id: 'armpits',
    name: 'Armhålor',
    areaId: 'arms'
  },
  
  // Legs zones
  {
    id: 'thighs',
    name: 'Lår',
    areaId: 'legs'
  },
  {
    id: 'calves',
    name: 'Vader',
    areaId: 'legs'
  },
  {
    id: 'knees',
    name: 'Knän',
    areaId: 'legs'
  },
  
  // Bikini zones
  {
    id: 'bikini-line',
    name: 'Bikinilinjen',
    areaId: 'bikini'
  },
  {
    id: 'bikini-full',
    name: 'Hela bikiniområdet',
    areaId: 'bikini'
  },
  
  // Brazilian zones
  {
    id: 'brazilian-full',
    name: 'Fullständig Brazilian',
    areaId: 'brazilian'
  },
  {
    id: 'brazilian-partial',
    name: 'Partiell Brazilian',
    areaId: 'brazilian'
  }
];
