
export interface BaseService {
  id: string;
  name: string;
  description: string;
  category: string;
}

export interface ProblemArea {
  id: string;
  name: string;
  description: string;
}

export interface TreatmentArea {
  id: string;
  name: string;
  bodyRegion: string;
}

export interface CompositeService {
  id?: string;
  baseServiceId: string;
  selectedEquipment: string[];
  selectedProblems: string[];
  selectedAreas: string[];
  customName: string;
  description: string;
  autoGeneratedKeywords: string[];
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export const BASE_SERVICES: BaseService[] = [
  {
    id: 'microneedling',
    name: 'Microneedling',
    description: 'Kollagenstimulering och hudförnyelse',
    category: 'aesthetic'
  },
  {
    id: 'ansiktsbehandling',
    name: 'Ansiktsbehandling',
    description: 'Grundläggande hudvård och rengöring',
    category: 'skincare'
  },
  {
    id: 'laserbehandling',
    name: 'Laserbehandling',
    description: 'Laserbaserade behandlingar',
    category: 'laser'
  },
  {
    id: 'kemisk-peeling',
    name: 'Kemisk Peeling',
    description: 'Syrabehandlingar för hudförnyelse',
    category: 'chemical'
  },
  {
    id: 'konsultation',
    name: 'Konsultation',
    description: 'Analys och rådgivning',
    category: 'consultation'
  }
];

export const PROBLEM_AREAS: ProblemArea[] = [
  {
    id: 'acne',
    name: 'Akne',
    description: 'Inflammerad och icke-inflammerad akne'
  },
  {
    id: 'scars',
    name: 'Ärr',
    description: 'Akneärr och andra hudärr'
  },
  {
    id: 'wrinkles',
    name: 'Rynkor',
    description: 'Fina linjer och djupare rynkor'
  },
  {
    id: 'pigmentation',
    name: 'Pigmentering',
    description: 'Ojämn pigmentering och fläckar'
  },
  {
    id: 'dry-skin',
    name: 'Torr hud',
    description: 'Uttorkad och irriterad hud'
  },
  {
    id: 'large-pores',
    name: 'Stora porer',
    description: 'Förstorade och synliga porer'
  },
  {
    id: 'dullness',
    name: 'Matt hud',
    description: 'Livlös och glansös hud'
  },
  {
    id: 'rosacea',
    name: 'Rosacea',
    description: 'Rodnad och känslig hud'
  },
  {
    id: 'hair-removal',
    name: 'Hårborttagning',
    description: 'Oönskad hårväxt'
  },
  {
    id: 'vascular-lesions',
    name: 'Kärlförändringar',
    description: 'Synliga blodkärl och rosacearodnad'
  }
];

export const TREATMENT_AREAS: TreatmentArea[] = [
  {
    id: 'face-full',
    name: 'Hela ansiktet',
    bodyRegion: 'face'
  },
  {
    id: 'face-forehead',
    name: 'Panna',
    bodyRegion: 'face'
  },
  {
    id: 'face-cheeks',
    name: 'Kinder',
    bodyRegion: 'face'
  },
  {
    id: 'face-nose',
    name: 'Näsa',
    bodyRegion: 'face'
  },
  {
    id: 'face-chin',
    name: 'Haka',
    bodyRegion: 'face'
  },
  {
    id: 'neck',
    name: 'Hals',
    bodyRegion: 'neck'
  },
  {
    id: 'decolletage',
    name: 'Dekolletage',
    bodyRegion: 'chest'
  },
  {
    id: 'hands',
    name: 'Händer',
    bodyRegion: 'hands'
  },
  {
    id: 'arms',
    name: 'Armar',
    bodyRegion: 'arms'
  },
  {
    id: 'legs',
    name: 'Ben',
    bodyRegion: 'legs'
  },
  {
    id: 'back',
    name: 'Rygg',
    bodyRegion: 'back'
  },
  {
    id: 'chest',
    name: 'Bröst',
    bodyRegion: 'chest'
  }
];
